"""add html_report field

Revision ID: 034b2394a5c1
Revises: dae0b9479291
Create Date: 2022-12-27 00:49:48.506197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034b2394a5c1'
down_revision = 'dae0b9479291'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('html_report', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'html_report')
    # ### end Alembic commands ###
