"""add forecast type to models table

Revision ID: 5462a057526d
Revises: 02fc43d87708
Create Date: 2023-06-10 13:30:34.896363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5462a057526d'
down_revision = '02fc43d87708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('type_forecast', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'type_forecast')
    # ### end Alembic commands ###
