"""create initial tables

Revision ID: dae0b9479291
Revises: 
Create Date: 2022-12-17 18:37:27.816323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae0b9479291'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('pkey', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('culture', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pkey')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=True)
    op.create_index(op.f('ix_clients_pkey'), 'clients', ['pkey'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('storage_name', sa.String(), nullable=True),
    sa.Column('time_trained', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('forecast_period', sa.Integer(), nullable=True),
    sa.Column('train_params', sa.String(), nullable=True),
    sa.Column('client_pkey', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_pkey'], ['clients.pkey'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_table('traintasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_finished', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_pkey', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['client_pkey'], ['clients.pkey'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traintasks_id'), 'traintasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traintasks_id'), table_name='traintasks')
    op.drop_table('traintasks')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_clients_pkey'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
