"""add model id to tasks table

Revision ID: 9ae801508331
Revises: 034b2394a5c1
Create Date: 2022-12-27 14:50:48.443415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae801508331'
down_revision = '034b2394a5c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traintasks', sa.Column('model_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traintasks', 'model_id')
    # ### end Alembic commands ###
