"""add error report field to task

Revision ID: 02fc43d87708
Revises: 4cd48a456c04
Create Date: 2023-01-23 22:39:32.471142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fc43d87708'
down_revision = '4cd48a456c04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traintasks', sa.Column('error_report', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traintasks', 'error_report')
    # ### end Alembic commands ###
