"""add n_lags

Revision ID: 4cd48a456c04
Revises: 9ae801508331
Create Date: 2023-01-22 23:57:06.564235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd48a456c04'
down_revision = '9ae801508331'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('n_lags', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'n_lags')
    # ### end Alembic commands ###
